version: '3.7'

services:

  wfs-tiler:
    build: .
    image: flaviostutz/wfs-tiler
    ports: 
      - 3000:3000
    restart: always
    environment:
      - WFS3_API_URL=http://wfsgis:8080
      - CACHE_CONTROL=public,max-age=3600

  map-demos:
    image: flaviostutz/map-demos
    ports:
      - 8181:80
    environment:
      - MAPBOX_VECTOR_TILE_URL=http://localhost:8282/tiles/tests/{z}/{x}/{y}.mvt
      # - MAPBOX_VECTOR_TILE_URL=http://localhost:3000/tiles/tests/{z}/{x}/{y}.mvt

  nginx-cache-proxy:
    image: flaviostutz/nginx-cache-proxy
    ports:
      - 8282:80
    environment:
      - PROXY_PASS_URL=http://wfs-tiler:3000/

  wfsgis:
    image: flaviostutz/wfsgis
    ports: 
      - 8080:8080
    restart: always
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DBNAME=admin

  postgis:
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin

